import './patent-analytics.css'
import StructureSlideshow from './StructureSlideshow'
import OpenLeadFormButton from './OpenLeadFormButton'
import LeadCaptureModal from './LeadCaptureModal'
import { LatestNewsTeaser, PatentNewsFeedSection } from './PatentNewsFeed'
import statsData from './stats-data.json'

const services = [
  {
    name: 'Genus/Species (Markush) Claim Coverage Analysis',
    desc: "Does a specific compound fall inside a patent's broad genus claim? Structural coverage testing built on real cheminformatics matching — not a keyword search.",
    flagship: true,
  },
  {
    name: 'Section 3(d) Compliance Screening',
    desc: 'India-specific: classifies whether a claimed compound is a salt, ester, isomer, or other "known substance" derivative, and flags whether efficacy data is present — the exact test Indian courts apply.',
  },
  {
    name: 'Prior-Art / FTO Structural Triage',
    desc: 'Fast first-pass structure search across multiple patents, before commissioning a full manual search.',
  },
  {
    name: 'Patent Family / Portfolio Landscape Reports',
    desc: 'An entire patent family around one drug or target, processed into a single consolidated structure database.',
  },
  {
    name: 'Ongoing Patent Monitoring',
    desc: 'Retainer-based alerts when new patents matching your compound classes are published.',
  },
  {
    name: 'CDMO Process FTO Pre-Screens',
    desc: 'Check a proposed synthetic route or target compound against existing process patents before committing manufacturing resources.',
  },
]

// Sourced from stats-data.json (regenerated by update_website_stats.py from
// real pipeline output), not hand-typed here -- see that script's docstring
// for the "later, live without redeploy" follow-up plan.
const stats = [
  { v: String(statsData.structuresTested), l: 'structures tested' },
  { v: String(statsData.realPatents), l: 'real patents' },
  { v: `${statsData.falsePositiveRatePercent}%`, l: 'false positives on auto-verified' },
  { v: `${statsData.autoVerifiedRatePercent}%`, l: 'auto-verified, zero errors measured' },
]

export default function PatentAnalyticsPage() {
  return (
    <div
      className="min-h-screen w-full"
      style={{
        // "Synthetix Light Spatial" design tokens, scoped to this page only.
        // Primary corrected to #0284c7 per the spec's own WCAG AA note
        // (overriding the slightly-off #006194 in its raw color table).
        // CSS custom properties aren't in React's CSSProperties type, hence
        // the cast rather than a per-line ts-expect-error (which wouldn't
        // reliably cover every key in this multi-line object).
        ...({
          '--surface': '#f7f9fb',
          '--surface-bright': '#ffffff',
          '--surface-container-low': '#f2f4f6',
          '--surface-container': '#eceef0',
          '--on-surface': '#191c1e',
          '--on-surface-variant': '#3f4850',
          '--on-surface-muted': '#64748b',
          '--outline-variant': '#bfc7d2',
          '--primary': '#0284c7',
          '--primary-container': '#007bb9',
          '--secondary': '#4b41e1',
          '--tertiary': '#00647c',
          '--tertiary-bright': '#0ea5c4',
          '--surface-glass': 'rgba(255, 255, 255, 0.7)',
          '--border-light': 'rgba(15, 23, 42, 0.08)',
          '--input-bg': '#f1f5f9',
        } as React.CSSProperties),
        background: 'var(--surface)',
        color: 'var(--on-surface)',
        fontFamily: 'var(--font-inter), Inter, sans-serif',
      }}
    >
      <LeadCaptureModal />

      {/* Header — brand wordmark deliberately larger than the hero H1 (per explicit direction) */}
      <header className="sticky top-0 z-50 w-full pa-glass" style={{ borderRadius: 0, borderLeft: 'none', borderRight: 'none', borderTop: 'none' }}>
        <div className="w-full px-6 md:px-12 py-5 flex items-center justify-between flex-wrap gap-4">
          <div className="flex items-center gap-3">
            <div
              className="w-11 h-11 rounded-lg flex items-center justify-center pa-scaffold-node shrink-0"
              style={{ background: `linear-gradient(135deg, var(--primary), var(--secondary))` }}
            >
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
                <circle cx="6" cy="6" r="2.5" fill="white" />
                <circle cx="18" cy="6" r="2.5" fill="white" />
                <circle cx="12" cy="16" r="2.5" fill="white" />
                <path d="M8 7.5L10.5 14.5M16 7.5L13.5 14.5M8.5 6H15.5" stroke="white" strokeWidth="1.2" />
              </svg>
            </div>
            <span className="pa-display text-[28px] md:text-[64px] font-bold leading-none">patent-analytics.thechemsolver.com</span>
          </div>
          <nav className="hidden md:flex items-center gap-1">
            <a href="#services" className="text-base px-3 py-2 rounded-lg hover:bg-black/[0.03] transition-colors" style={{ color: 'var(--on-surface-variant)' }}>Services</a>
            <a href="#proof" className="text-base px-3 py-2 rounded-lg hover:bg-black/[0.03] transition-colors" style={{ color: 'var(--on-surface-variant)' }}>Measured Accuracy</a>
            <a href="#about" className="text-base px-3 py-2 rounded-lg hover:bg-black/[0.03] transition-colors" style={{ color: 'var(--on-surface-variant)' }}>About</a>
          </nav>
          <div className="flex items-center gap-3">
            <LatestNewsTeaser />
            <OpenLeadFormButton className="pa-btn-primary text-base font-medium px-5 py-2.5">
              Free sample →
            </OpenLeadFormButton>
          </div>
        </div>
      </header>

      {/* Hero — full-width bento split */}
      <section className="w-full px-6 md:px-12 py-16 md:py-24">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center max-w-[1400px] mx-auto">
          <div className="lg:col-span-7">
            <div className="pa-chip mb-6">
              <span className="w-1.5 h-1.5 rounded-full" style={{ background: 'var(--tertiary-bright)' }} />
              Chemistry-grade patent analysis, tested and measured
            </div>
            <h1 className="pa-display text-[40px] md:text-[56px] font-bold leading-[1.05] mb-6" style={{ color: 'var(--on-surface)' }}>
              Chemical structure &amp;<br />genus-claim analysis<br />
              <span style={{ color: 'var(--primary)' }}>for patent teams</span>
            </h1>
            <p className="text-lg leading-relaxed mb-8 max-w-xl" style={{ color: 'var(--on-surface-variant)' }}>
              We extract, verify, and analyze chemical structures from patent documents —
              including the genus/species (Markush) coverage question that decided
              cases like <em>Natco v. Roche</em> and <em>AstraZeneca v. Intas</em>. Every
              report is honest about what&rsquo;s independently confirmed and what still
              needs your review.
            </p>
            <div className="flex flex-wrap gap-3">
              <OpenLeadFormButton className="pa-btn-primary text-base font-semibold px-6 py-3.5">
                Request a free sample report →
              </OpenLeadFormButton>
              <a href="#services" className="pa-btn-ghost text-base font-semibold px-6 py-3.5 inline-block">
                See all services
              </a>
            </div>
          </div>

          {/* Real extracted structures, auto-advancing */}
          <div className="lg:col-span-5 relative h-[380px] hidden lg:block">
            <StructureSlideshow />
            <div
              className="pa-glass absolute -bottom-4 -left-4 px-4 py-3"
              style={{ transform: 'perspective(1000px) rotateY(-6deg) rotateX(3deg) translateZ(20px)' }}
            >
              <div className="pa-mono text-xs" style={{ color: 'var(--on-surface-muted)' }}>LIVE EXTRACTION</div>
              <div className="text-base font-semibold" style={{ color: 'var(--tertiary)' }}>Real structures, real patents</div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats bento row */}
      <section id="proof" className="w-full px-6 md:px-12 pb-16">
        <div className="max-w-[1400px] mx-auto">
          <div className="pa-mono text-sm uppercase mb-4" style={{ color: 'var(--on-surface-muted)' }}>Measured, not marketed</div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {stats.map((s) => (
              <div key={s.l} className="pa-glass p-5">
                <div className="pa-display text-4xl font-bold mb-1" style={{ color: 'var(--primary)' }}>{s.v}</div>
                <div className="text-base leading-snug" style={{ color: 'var(--on-surface-variant)' }}>{s.l}</div>
              </div>
            ))}
          </div>
          <p className="text-base mt-5 max-w-2xl leading-relaxed" style={{ color: 'var(--on-surface-muted)' }}>
            Every structure in a report is labeled either{' '}
            <b style={{ color: 'var(--tertiary)' }}>Verified</b> (passed automated
            chemical validation and was independently confirmed against a second,
            unrelated source) or <b style={{ color: 'var(--secondary)' }}>Needs review</b> —
            never presented as fact when it isn&rsquo;t one.
          </p>
        </div>
      </section>

      {/* Services bento grid */}
      <section id="services" className="w-full px-6 md:px-12 py-16" style={{ background: 'var(--surface-container-low)' }}>
        <div className="max-w-[1400px] mx-auto">
          <h2 className="pa-display text-3xl font-bold mb-2">Services</h2>
          <p className="text-base mb-10" style={{ color: 'var(--on-surface-muted)' }}>
            The structure-extraction report is our free sample. Everything below is
            what we can build out for your team.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {services.map((s) => (
              <div
                key={s.name}
                className="pa-glass p-6"
                style={s.flagship ? { borderTop: '2px solid var(--tertiary-bright)' } : undefined}
              >
                <div className="flex items-center gap-2 mb-2 flex-wrap">
                  <h3 className="font-semibold text-base">{s.name}</h3>
                  {s.flagship && (
                    <span className="pa-chip" style={{ padding: '2px 10px', fontSize: '11px' }}>Flagship</span>
                  )}
                </div>
                <p className="text-base leading-relaxed" style={{ color: 'var(--on-surface-variant)' }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Founder credibility */}
      <section id="about" className="w-full px-6 md:px-12 py-16">
        <div className="max-w-[1400px] mx-auto grid md:grid-cols-2 gap-6">
          <div className="pa-glass p-8">
            <h2 className="pa-display text-xl font-bold mb-4">Who&rsquo;s behind this</h2>
            <p className="text-base leading-relaxed" style={{ color: 'var(--on-surface-variant)' }}>
              Built by <b style={{ color: 'var(--on-surface)' }}>Prashant Kotian</b>, a
              chemistry researcher pursuing a PhD in Chemistry at the Institute of
              Chemical Technology (ICT), Mumbai, with 9+ years teaching organic and
              analytical chemistry for IIT-JEE and NEET, and founder of TheChemSolver
              and Chem-Mantra — chemistry education platforms combined serving 300+
              interactive simulations and 22,000+ practice questions. This
              patent-analytics work applies the same structure-verification rigor
              built into those platforms&rsquo; chemistry engines to real patent documents.
            </p>
          </div>
          <div className="pa-glass p-8">
            <h2 className="pa-display text-xl font-bold mb-4">What we don&rsquo;t claim</h2>
            <p className="text-base leading-relaxed" style={{ color: 'var(--on-surface-variant)' }}>
              Our reports identify chemical structures and their relationships to
              claimed scope — they do not assert legal conclusions (infringement,
              validity, disclosure/enablement). That judgment stays with you and your
              counsel. Every report explicitly separates what was independently
              confirmed from what still needs your review.
            </p>
          </div>
        </div>
      </section>

      <PatentNewsFeedSection />

      {/* CTA */}
      <section className="w-full px-6 md:px-12 py-20">
        <div className="max-w-[1400px] mx-auto pa-glass pa-glass-elevated text-center py-16 px-6" style={{ background: 'linear-gradient(180deg, rgba(2,132,199,0.04), var(--surface-glass))' }}>
          <h2 className="pa-display text-2xl md:text-3xl font-bold mb-3">Request a free sample report</h2>
          <p className="text-base mb-8 max-w-xl mx-auto" style={{ color: 'var(--on-surface-variant)' }}>
            Fill in your details and get instant access to a real structure-extraction
            report — no cost, no obligation.
          </p>
          <OpenLeadFormButton className="pa-btn-primary text-base font-semibold px-8 py-4">
            Get my free sample report →
          </OpenLeadFormButton>
        </div>
      </section>

      {/* Footer — own, no TheChemSolver branding */}
      <footer className="w-full px-6 md:px-12 py-8 border-t text-center" style={{ borderColor: 'var(--border-light)' }}>
        <p className="pa-mono text-sm" style={{ color: 'var(--on-surface-muted)' }}>
          patent-analytics.thechemsolver.com · support@thechemsolver.com
        </p>
      </footer>
    </div>
  )
}
