import { jsPDF } from 'jspdf'

const PAGE_WIDTH = 595.28 // A4 pt
const PAGE_HEIGHT = 841.89
const MARGIN = 48
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2

/**
 * Generic JSON -> readable PDF renderer. Deliberately not a per-product
 * bespoke template -- report shapes vary (portfolio_landscape has a
 * `structures` array that can run to hundreds of entries, fto_triage has a
 * couple of SMILES strings) and a single walker that handles primitives,
 * arrays, and nested objects covers all of them without hand-maintaining
 * one layout per product_type.
 */
export function buildReportPdf(title: string, subtitle: string, data: Record<string, unknown>): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  let y = MARGIN

  function ensureSpace(need: number) {
    if (y + need > PAGE_HEIGHT - MARGIN) {
      doc.addPage()
      y = MARGIN
    }
  }

  function writeLines(text: string, x: number, fontSize: number, lineHeight: number, maxWidth: number) {
    doc.setFontSize(fontSize)
    const lines: string[] = doc.splitTextToSize(text, maxWidth)
    for (const line of lines) {
      ensureSpace(lineHeight)
      doc.text(line, x, y)
      y += lineHeight
    }
  }

  doc.setFont('helvetica', 'bold')
  writeLines(title, MARGIN, 18, 22, CONTENT_WIDTH)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(90)
  writeLines(subtitle, MARGIN, 11, 15, CONTENT_WIDTH)
  doc.setTextColor(0)
  y += 6
  ensureSpace(1)
  doc.setDrawColor(200)
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y)
  y += 18

  function renderValue(key: string, value: unknown, indent: number) {
    const x = MARGIN + indent
    const maxWidth = CONTENT_WIDTH - indent
    const label = humanizeKey(key)

    if (value === null || value === undefined || value === '') {
      return
    }

    if (Array.isArray(value)) {
      if (value.length === 0) return
      const isObjectArray = typeof value[0] === 'object' && value[0] !== null
      doc.setFont('helvetica', 'bold')
      writeLines(`${label} (${value.length})`, x, 11, 15, maxWidth)
      doc.setFont('helvetica', 'normal')
      if (isObjectArray) {
        value.forEach((item, i) => {
          ensureSpace(14)
          doc.setFont('helvetica', 'bold')
          writeLines(`  ${i + 1}.`, x, 10, 13, maxWidth)
          doc.setFont('helvetica', 'normal')
          Object.entries(item as Record<string, unknown>).forEach(([k, v]) => renderValue(k, v, indent + 24))
          y += 4
        })
      } else {
        value.forEach((item) => writeLines(`  •  ${String(item)}`, x, 10, 13, maxWidth))
      }
      y += 4
      return
    }

    if (typeof value === 'object') {
      doc.setFont('helvetica', 'bold')
      writeLines(label, x, 11, 15, maxWidth)
      doc.setFont('helvetica', 'normal')
      Object.entries(value as Record<string, unknown>).forEach(([k, v]) => renderValue(k, v, indent + 16))
      y += 4
      return
    }

    doc.setFont('helvetica', 'bold')
    const labelWidth = doc.getTextWidth(`${label}: `)
    doc.text(`${label}: `, x, ensureSpaceInline(12))
    doc.setFont('helvetica', 'normal')
    writeLines(String(value), x + labelWidth, 10, 13, maxWidth - labelWidth)
  }

  function ensureSpaceInline(need: number): number {
    ensureSpace(need)
    return y
  }

  Object.entries(data).forEach(([key, value]) => renderValue(key, value, 0))

  ensureSpace(30)
  y += 10
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text(`Generated by patent-analytics.thechemsolver.com — ${new Date().toISOString().slice(0, 10)}`, MARGIN, y)

  return doc
}

function humanizeKey(key: string): string {
  return key
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}
